### ISSUE TITLE
View List of products

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#12]
As a Site User, I want to be able to see a list of products so that I can select one.

**Acceptance Criteria**
 

- Page listing all products:
- Page listing products of same category

** Tasks**

- [x] Create Product Model
- [x] Create  the view code 
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
