### ISSUE TITLE
View Product Detail

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#13]
As a Shopper, I want to be able to click on a product so that I can read the details

**Acceptance Criteria**

- Product details page listing all  necessary information
-  Product image, title, description, quantity and price

**Tasks**

- [x] Create  the view code 
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
