### ISSUE TITLE
View Category

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#14]
As a Shopper, I want to be able to able to view a specific category so that I can select a precise type of products.

**Acceptance Criteria**

 Secondary Navbar under "Products" a drop down menu should be displayed
 Once a category has been clicked the user is redirected to the specific category view

**Tasks**

- [x] Create a Model
- [x] Create the categories in the admin panel
- [x] Create  the view code 
- [x] Create a template to render the view
- [x] Connect URLs  in the urls.py file
- [x] Write GET request logic in all_products view to filter products by category
