### ISSUE TITLE
Sort product

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#16]
As a Shopper, I want to be able to sort all products with a filter so that I can view products based on price or title

**Acceptance Criteria**

- Each list product pages should display a sort products drop-down menu
- Drop-down arrow indicates pre-defined sort options
- Once the option selected the page give the products according the chosen filter

**Tasks**

- [x] Create sort selector on products page 
- [x] Add GET request to the all_products view 
- [x]  Write javascript to update product list selected
