### ISSUE TITLE
Register an account

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#17]
As a Site User, I want to be able to register an account so that I can save personal information and be allowed to leave reviews.

**Acceptance Criteria**

Signup link in the user drop down menu  in the navbar
Secure Signup form
Email confirmation once the form is filled in and sent
Success message creation of a new account should be displayed

**Tasks**

#2 

- [x]  Add email verification requirement
- [x]  Set up Gmail to send emails and add details to settings.py
- [x]  Add signup link to navbar
- [x]  Customise allauth signup form HTML templates
- [x]  Create message to notify user of successful signup
