### ISSUE TITLE
Login or logout

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#18]
As a Site User I want to be able to log in/out of my account so that I can access my personal profile and  keep my account secure.
As a site user I can see my login status so that I know if I'm logged in or out.

**Acceptance Criteria**

-  Simple login/logout form
-  Only accessible for registered users
-  Sign in button should be visible on the nav bar
-  Success message notification when the user has logged in properly
-   Username options should appear in the user menu when the user has logged in
-  Error message notification in case unqualified info were entered

**Tasks**
#2 and #17

- [x]  Add log in and log out links to navbar
- [x]  Customise allauth login, logout HTML templates
- [x]  Create success messages for successful login/logout
- [x]   Include logic in the Navbar to check if user is authenticated
- [x]  Adaptable display options according status of the user
