### ISSUE TITLE
View order history

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#21]
As a site user I want to be able to view my order history so that I can remember what purchases I've made.

**Acceptance Criteria**

logged in user can access their history in their profile
Detail Order is displayed once one order has been clicked

**Tasks**

- [x]  Add the users profile to the order in the checkout success view
- [x]  Update profile html template to include the order history
- [x]  Link order number to checkout success html page
