### ISSUE TITLE
View Bag

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#23]
As a shopper I want to be able to  view a the contents of my shopping bag at any time so I can keep myself informed about my selection and the total cost.

**Acceptance Criteria**

- Bag page listing all selected item
- Displaying  unit price, quantity and subtotal

**Tasks**

- [x]  Create template and URL.
- [x]  Create view_bag view
- [x] Connect URLs in the urls.py file
- [x]  Add link to shopping bag to the navbar.
- [x]  Create context.py in the bag app and add to settings.py.
- [x]  Style bag.html page
