### ISSUE TITLE
View Bag - Add Product

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#24]
As a shopper, I want to be able tp add a number of products in different quantities to my shopping bag so that I can change which items and how many I buy before checkout and purchase them all at once when I am ready.

**Acceptance Criteria**

- Quantity selector and Add Bag Button should be displayed in Detail Page
- Min/Max threshold for quantities should be set

**Tasks**

- [x]  Create add to bag form within the product_detail.html template.
- [x]  Create add_to_bag view 
- [x] Connect URLs in the urls.py file
- [x]  Add bag content to context processor
- [x]  Add javascript to increase/decrease quantity in bag
- [x]  Style add to bag button and quantity selector.
