### ISSUE TITLE
View Bag  Track  Total

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#25]
As a shopper, I want to be able to view a running total of my shopping bag as I am shopping so that I can see how much it costs in total.

**Acceptance Criteria**

-  Running total cost of order can be displayed on all pages

**Tasks**

- [x] Create a toast  template for the success message.
- [x]  Add success message to add to bag view.
- [x]  Include the Shopping bag running total in success template.
