### ISSUE TITLE
View Bag -Update

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#27]
As a shopper I want to be able to  adjust the quantity of individual products in my bag so that I can make changes before I purchase.

**Acceptance Criteria**

- Bag view with update/delete product options
- Quantity of each product line item can be adjusted and the subtotal updated accordingly.

**Tasks**

- [x] Add quantity selector buttons and update/delete buttons to the shopping bag page.
- [x]  Write javascript to increase/decrease the quantity when the button is clicked
- [x]  Write javascript to update the cart when the update button is clicked
- [x]  Write javascript to delete the product line items when the delete button is clicked.
- [x]  Create adjust_bag and delete_item views 
- [x] Connect URLs in the urls.py file
