### ISSUE TITLE
View Order Confirmation

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#28]
As a shopper, I want to be able to  view an order confirmation after checkout so that I  can know my purchase was successful.

**Acceptance Criteria**

-  New page after successful checkout displaying personal and billing info and order content

**Tasks**

- [x]  Create Checkout Success view
- [x]  Create Checkout Success template
- [x]  Connect URLs in the urls.py file
