### ISSUE TITLE
Order Confirmation Email

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#29]
As a shopper, I want to be able to receive an email confirmation of my order so that I can have a record of my purchase.

**Acceptance Criteria**

- Confirmation email to user after checkout
-  Email contains billing and delivery info as well as order contents

**Tasks**

- [x] Create email templates for order confirmation
- [x]  Update webhook handler to handle sending confirmation email
- [x]  Set up Gmail to send emails
