### ISSUE TITLE
Payment Details

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#30]
As a shopper, I want to be able to enter my payment information securely so that I can purchase my chosen products quickly with no issues.

**Acceptance Criteria**

- Clearly labeled payment form for billing and delivery information
-  Form pre-populated for registered users with profile

**Tasks**

- [x]  Utilising Stripe Elements, create a Credit Card Details section in the Order Form and embed the Stripe UI component.
- [x]  Add custom styling to Stripe Elements.
- [x]  Add Stripe code to Checkout view.
- [x]  Include Stripe Javascript
- [x]  Use Stripe Webhooks
