### ISSUE TITLE
View Product Management

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#32]
As a store owner, want to ba able to add products through an easy-to-use interface so that I can manage the store's contents.

**Acceptance Criteria**

-  Product submission form on front end
-  Feature only accessible to admin users

**tasks**

- [x]  Create product form.py
- [x] Create template
- [x] Create an "Add Product" link
- [x]  Include error/success messages to give feedback to the user
