### ISSUE TITLE
View Review

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#37]
As a site user, I want to be able to read reviews left by other customers so that I can have feedback insights from customers

**Acceptance criteria**

A list of reviews has been displayed

**Tasks**

- [x] Create the view code 
- [x]  Create a template to render the view
- [x]  Connect URLs in the urls.py file
