### ISSUE TITLE
View Delete Review

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#40]
As a site user, I want to be able to delete  a review regarding one of the products in the site so that I can decide to how long my feedbacks are accessible.

**Acceptance Criteria**

- A delete page has been displayed with btn to execute action

**Tasks**

- [x]  Create the view code
- [x]  Create a template to render the view
- [x]  Connect URLs in the urls.py file
