### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#41]
As a site user, I want to be able to  sign up for the website's newsletter so that I can keep up to date with new products and promotions

**Acceptance Criteria**

- Simple sign up form in t he footer is displayed

**Tasks**

- [x]  Set up mailchimp
- [x]  Add mailchimp HTML and JS to footer.
- [x]  Style footer using CSS
