### ISSUE TITLE
Create the Heroku app

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#5]
As a developer, I need to host my digital product so that user can use it.

**Acceptance Criteria**

An empty app has been deployed with all Key/Variable configuration required for the production

**Tasks**

- [x] Create new Heroku App
- [x] Add Config Var
- [x] Create new env.py file on top level directory
- [x] In env.py: Import os library
- [x] In env.py: Set environment variables (os.environ["DATABASE_URL"] = "Paste in ElephantSQL database URL")
- [x] In env.py: Add in secret key
- [x] Add Secret Key to Config Vars
- [x] In settings.py: Reference env.py
- [x] Remove the insecure secret key and replace - links to the SECRET_KEY
- [x] Comment out the old DataBases Section
- [x] Add new DATABASES Section
- [x] Save all files and Make Migrations
- [x] Add Aws key/Id to Heroku Config Var
- [x] Change the templates directory
- [x] Add Heroku Hostname to ALLOWED_HOSTS
- [x] Create procfile on the top level directory
- [x] Add code: web: gunicorn PROJ_NAME.wsgi
- [x] Add, Commit and Push
