### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by bakrydiarra** [bakrydiarra/Lotus#6]
As a user I want to be able to have intuitive User Interface so that I can  easily navigate

**Acceptance criteria**

- A Navbar has been displayed with identified links to suit the navigation
- A Navbar should collapse to a burger menu for smaller screen sizes.

**Tasks**

Create a responsive Navbar

- [x] Bootstrap core  responsive design
- [x] Personalise placement of the items
- [x] style links
- [x] django tags to differentiate navbar for  visitors from  authenticated users
